language: haxe

sudo: false

addons:
  apt:
    packages:
    - g++-multilib
    - gcc-multilib
    - mesa-common-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libgc-dev
    - libgtk-3-dev

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32 -extension GLX"
  - "export AUDIODEV=null"

install:
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp > log.txt || cat log.txt
  - haxelib install format > log.txt || cat log.txt
  - git clone --recursive https://github.com/openfl/lime-samples ~/lime-samples --depth 1
  - haxelib dev lime-samples ~/lime-samples
  - haxelib dev lime $(pwd)

script:
  - haxelib run lime rebuild linux -64 -Dlegacy > log.txt || cat log.txt
  - haxelib run lime rebuild linux -64 > log.txt || cat log.txt
  - haxelib run lime rebuild tools
  #- haxelib run lime create HandlingInputEvents
  - haxelib run lime create HelloWorld
  - haxelib run lime create SimpleAudio
  - haxelib run lime create SimpleImage
  - haxelib run lime create TextRendering
  #- haxelib run lime build HandlingInputEvents html5
  - haxelib run lime build HelloWorld html5
  - haxelib run lime build SimpleAudio html5
  - haxelib run lime build SimpleImage html5
  #- haxelib run lime build TextRendering html5
  #- haxelib run lime build HandlingInputEvents flash
  - haxelib run lime build HelloWorld flash
  - haxelib run lime build SimpleAudio flash
  - haxelib run lime build SimpleImage flash
  #- haxelib run lime build TextRendering flash
  #- haxelib run lime build HandlingInputEvents neko
  - haxelib run lime build HelloWorld neko
  - haxelib run lime build SimpleAudio neko
  - haxelib run lime build SimpleImage neko
  - haxelib run lime build TextRendering neko

notifications:
  slack: openfl:sBwVO0kgB7EuWLYzZzUezVIz

cache:
  directories:
    - ~/haxelib
