version: 2
jobs:

  Setup (Haxe 3.4.x):
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    working_directory: /workspace/lime
    steps:
     - checkout
     - run:
         name: Update Git Submodules
         command: git submodule update --init
     - run:
         name: Set Lime Development Directory
         command: haxelib dev lime .
     - run:
         name: Clone HXP
         command: git clone --single-branch --recursive https://github.com/openfl/hxp ../hxp --depth 1
     - run:
         name: Set HXP Development Directory
         command: haxelib dev hxp ../hxp
     - run:
         name: Rebuild Lime Tools
         command: haxelib run lime rebuild tools -nocffi
     - run:
         name: Clone Lime Samples
         command: git clone --recursive https://github.com/openfl/lime-samples ../lime-samples --depth 1
     - run:
         name: Set Lime Samples Development Directory
         command: haxelib dev lime-samples ../lime-samples
     - persist_to_workspace:
         root: /
         paths:
          - usr/local/lib/haxe/lib/*/.dev
          - workspace
  
  HTML5 (Haxe 3.4.x):
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - attach_workspace:
         at: /
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime build HelloWorld html5
     - run: haxelib run lime build SimpleAudio html5
     - run: haxelib run lime build SimpleImage html5
     - run: haxelib run lime build HelloWorld html5 -Dcanvas
     - run: haxelib run lime build SimpleAudio html5 -Dcanvas
     - run: haxelib run lime build SimpleImage html5 -Dcanvas
     - run: haxelib run lime build HelloWorld html5 -Ddom
     - run: haxelib run lime build SimpleAudio html5 -Ddom
     - run: haxelib run lime build SimpleImage html5 -Ddom
  
  Neko (Haxe 3.4.x):
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - attach_workspace:
         at: /
     - run: haxelib run lime rebuild linux -release -64 -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime build HelloWorld neko
     - run: haxelib run lime build SimpleAudio neko
     - run: haxelib run lime build SimpleImage neko
     - run: haxelib run lime build HelloWorld neko -Dcairo
     - run: haxelib run lime build SimpleAudio neko -Dcairo
     - run: haxelib run lime build SimpleImage neko -Dcairo
  
  C++ (Haxe 3.4.x):
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - attach_workspace:
         at: /
     - run: haxelib run lime rebuild linux -release -64 -nocffi
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime build HelloWorld linux
     - run: haxelib run lime build SimpleAudio linux
     - run: haxelib run lime build SimpleImage linux
  
  Flash (Haxe 3.4.x):
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.2
    steps:
     - attach_workspace:
         at: /
     - run: haxelib run lime create HelloWorld
     - run: haxelib run lime create SimpleAudio
     - run: haxelib run lime create SimpleImage
     - run: haxelib run lime build HelloWorld flash
     - run: haxelib run lime build SimpleAudio flash
     - run: haxelib run lime build SimpleImage flash
  
  Documentation (Haxe 3.4.x):
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.5
    working_directory: /workspace/lime/docs/api
    steps:
     - attach_workspace:
         at: /
     - run:
         name: Clone Dox
         command: git clone https://github.com/openfl/dox ~/dox --depth 1
     - run:
         name: Set Dox Development Directory
         command: haxelib dev dox ~/dox
     - run:
         name: Generate Documentation
         command: haxe build.hxml
     - run:
         name: Deploy
         command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              aws s3 sync docs-api s3://api.lime.software --acl bucket-owner-full-control --acl public-read --size-only --delete --include="*" --cache-control max-age=864000
            else
              echo "Not on master (skipping step)"
            fi


workflows:
  version: 2
  
  Tests (Haxe 3.4.x):
    jobs:
     - Setup (Haxe 3.4.x)
     - HTML5 (Haxe 3.4.x):
         requires:
          - Setup (Haxe 3.4.x)
     - Neko (Haxe 3.4.x):
         requires:
          - Setup (Haxe 3.4.x)
     - C++ (Haxe 3.4.x):
         requires:
          - Setup (Haxe 3.4.x)
     - Flash (Haxe 3.4.x):
         requires:
          - Setup (Haxe 3.4.x)
     - Documentation (Haxe 3.4.x):
         requires:
          - Setup (Haxe 3.4.x)