name: CI

on: [push]

jobs:

  build-linux:
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Setup environment
      run: |
        sudo apt-get install -y haxe libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev
        #sudo apt-get install -y build-essential git curl python
        #curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
        #sudo pip install awscli awsebcli
      
    - name: Install dependencies
      run: |
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib install hxcpp
        git clone https://github.com/jgranick/format $GITHUB_WORKSPACE/format --depth 1
        haxelib dev format $GITHUB_WORKSPACE/format
        haxelib install mcover
        haxelib install hamcrest
        git clone https://github.com/openfl/munit $GITHUB_WORKSPACE/munit --depth 1
        haxelib dev munit $GITHUB_WORKSPACE/munit/src
        cd $GITHUB_WORKSPACE/munit/tool && haxe build.hxml
        haxelib install format
        haxelib install hxp
       
    - name: Install "lime" command alias
      run: |
        haxelib dev lime $GITHUB_WORKSPACE
        haxelib run lime setup -alias -y
        
    - name: Rebuild Lime tools
      run: |
        lime rebuild hxcpp linux -static
        lime rebuild tools -nocolor -verbose
      
    - name: Rebuild Lime binaries
      run: |
        lime rebuild linux -64 -release -verbose -nocolor
        lime rebuild linux -32 -release -verbose -nocolor
        #lime rebuild android -release -verbose -nocolor
        lime rebuild hl -64 -release -verbose -nocolor
        
  build-macos:
    runs-on: macOS-10.14
    #env:
      #MACOSX_VER: 10.13
      #MACOSX_DEPLOYMENT_TARGET: 10.9 
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Setup environment
      run: |
        brew install haxe
      
    - name: Install dependencies
      run: |
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib install hxcpp
        git clone https://github.com/jgranick/format $GITHUB_WORKSPACE/format --depth 1
        haxelib dev format $GITHUB_WORKSPACE/format
        haxelib install mcover
        haxelib install hamcrest
        git clone https://github.com/openfl/munit $GITHUB_WORKSPACE/munit --depth 1
        haxelib dev munit $GITHUB_WORKSPACE/munit/src
        cd $GITHUB_WORKSPACE/munit/tool && haxe build.hxml
        haxelib install format
        haxelib install hxp
       
    - name: Install "lime" command alias
      run: |
        haxelib dev lime $GITHUB_WORKSPACE
        haxelib run lime setup -alias -y
        
    - name: Rebuild Lime tools
      run: |
        lime rebuild tools -nocolor -verbose
      
    - name: Rebuild Lime binaries
      run: |
        #lime rebuild mac -release -verbose -nocolor -DMACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET
        #lime rebuild hl -release -verbose -nocolor -DMACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET
        lime rebuild mac -release -verbose -nocolor
        lime rebuild hl -release -verbose -nocolor
        lime rebuild ios -release -verbose -nocolor

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Setup environment
      run: |
        choco install haxe
      
    - name: Install dependencies
      run: |
        haxelib install hxcpp
        git clone https://github.com/jgranick/format $GITHUB_WORKSPACE/format --depth 1
        haxelib dev format $GITHUB_WORKSPACE/format
        haxelib install mcover
        haxelib install hamcrest
        git clone https://github.com/openfl/munit $GITHUB_WORKSPACE/munit --depth 1
        haxelib dev munit $GITHUB_WORKSPACE/munit/src
        cd $GITHUB_WORKSPACE/munit/tool && haxe build.hxml
        haxelib install format
        haxelib install hxp
       
    - name: Install "lime" command alias
      run: |
        haxelib dev lime $GITHUB_WORKSPACE
        haxelib run lime setup -alias -y
        
    - name: Rebuild Lime tools
      run: |
        lime rebuild tools -nocolor -verbose
      
    - name: Rebuild Lime binaries
      run: |
        REM set HXCPP_MSVC=%env.VS100COMNTOOLS%
        lime rebuild windows -32 -release -verbose -nocolor
        lime rebuild hl -32 -release -verbose -nocolor
        REM set HXCPP_MSVC=
        lime rebuild windows -64 -release -verbose -nocolor
